version: "3.5"
services:
 jmeter:
    image: leandrovo/jmeter:1.0
    hostname: jmeter
    restart: always
    volumes:
      - ${PWD}/scripts:/opt/jmeter/scripts
    environment:
      BASE_URL_1: "nginx"
      HTTP_PORT: "80"
      USERNAME: "jsmith@demo.io"
      PASSWORD: "Demo123!"
      BASE_URL_API_GATEWAY: "bank"
      BASE_GATEWAY_PORT: "8081"


