receivers:
  otlp:
    protocols:
      grpc:
      http:        

exporters:
  logging:
    loglevel: debug
  otlphttp: 
    auth:
      authenticator: oauth2client
    traces_endpoint: https://xxx/data/v1/trace

processors:
  batch: #### Optional for trace batching for AppDynamics Cloud
    send_batch_max_size: 1000
    send_batch_size: 1000
    timeout: 10s

extensions: #### Mandatory for AppDynamics Cloud
  oauth2client:
    client_id: xxx
    client_secret: xxx
    token_url: xxx

service:
  extensions: #### Mandatory for AppD Cloud
    - oauth2client
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
  telemetry:
    logs:
      level: "debug"
