apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: inventory-instrumentation
  namespace: inventory{{ .Values.username }}
spec:
  exporter:
    endpoint: http://appdynamics-otel-collector-service.appdynamics.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest    
 
